# Generated by Django 6.0.3 on 2026-03-15 05:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Agent 唯一标识符",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Agent 名称，全局唯一", max_length=100, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", help_text="Agent 描述"),
                ),
                (
                    "api_key_hash",
                    models.CharField(
                        help_text="API Key 的 SHA256 hash", max_length=128, unique=True
                    ),
                ),
                (
                    "api_key_prefix",
                    models.CharField(
                        help_text="API Key 前缀，用于快速识别，如 'claw_live_xxx'",
                        max_length=20,
                    ),
                ),
                (
                    "claim_token",
                    models.CharField(
                        help_text="用于生成 claim_url 的 token",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "claim_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Claim"),
                            ("claimed", "Claimed"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        help_text="认领状态",
                        max_length=20,
                    ),
                ),
                (
                    "claim_expires_at",
                    models.DateTimeField(
                        blank=True, help_text="认领链接过期时间", null=True
                    ),
                ),
                (
                    "twitter_handle",
                    models.CharField(
                        blank=True,
                        help_text="认领者的 Twitter 用户名",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "tweet_url",
                    models.URLField(blank=True, help_text="验证推文的 URL", null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="创建时间"),
                ),
                (
                    "claimed_at",
                    models.DateTimeField(
                        blank=True, help_text="认领完成时间", null=True
                    ),
                ),
                (
                    "last_active_at",
                    models.DateTimeField(
                        blank=True, help_text="最后活动时间", null=True
                    ),
                ),
                ("level", models.IntegerField(default=1, help_text="等级")),
                ("experience", models.IntegerField(default=0, help_text="经验值")),
                (
                    "evennia_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="关联的 Evennia Account",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent",
                "verbose_name_plural": "Agents",
                "db_table": "agent_auth_agents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "connected_at",
                    models.DateTimeField(auto_now_add=True, help_text="连接时间"),
                ),
                (
                    "disconnected_at",
                    models.DateTimeField(blank=True, help_text="断开时间", null=True),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="连接 IP 地址", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, help_text="客户端 User Agent", max_length=255
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        help_text="关联的 Agent",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="agent_auth.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Session",
                "verbose_name_plural": "Agent Sessions",
                "db_table": "agent_auth_sessions",
                "ordering": ["-connected_at"],
            },
        ),
    ]
