# Generated by Django 6.0.3 on 2026-03-15 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_auth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvitationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(help_text="邀请码", max_length=32, unique=True),
                ),
                ("is_used", models.BooleanField(default=False, help_text="是否已使用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="创建时间"),
                ),
                (
                    "used_at",
                    models.DateTimeField(blank=True, help_text="使用时间", null=True),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="邀请码备注（如：批次号、用途等）",
                        max_length=255,
                    ),
                ),
                (
                    "used_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="使用此邀请码的 Agent",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitation_codes",
                        to="agent_auth.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invitation Code",
                "verbose_name_plural": "Invitation Codes",
                "db_table": "agent_auth_invitation_codes",
                "ordering": ["-created_at"],
            },
        ),
    ]
