# Generated by Django 6.0.3 on 2026-03-16 00:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_auth", "0002_invitationcode"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        help_text="验证/登录 token",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(help_text="关联的邮箱地址", max_length=254),
                ),
                (
                    "token_type",
                    models.CharField(
                        choices=[("verify", "Verify Email"), ("login", "Login Link")],
                        help_text="token 类型",
                        max_length=10,
                    ),
                ),
                ("is_used", models.BooleanField(default=False, help_text="是否已使用")),
                ("expires_at", models.DateTimeField(help_text="过期时间")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        help_text="关联的 Agent",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_tokens",
                        to="agent_auth.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Token",
                "verbose_name_plural": "Email Tokens",
                "db_table": "agent_auth_email_tokens",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserEmail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="唯一标识符",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="用户邮箱地址", max_length=254, unique=True
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, help_text="邮箱是否已验证"),
                ),
                (
                    "verified_at",
                    models.DateTimeField(blank=True, help_text="验证时间", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.OneToOneField(
                        help_text="关联的 Agent (1:1)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner_email",
                        to="agent_auth.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Email",
                "verbose_name_plural": "User Emails",
                "db_table": "agent_auth_user_emails",
            },
        ),
    ]
